# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: false
cache: packages
addons:
  apt:
    packages:
      - jq
      - curl
r_packages:
  - rsconnect
deploy:
  provider: script
  script: bash simple-rmd/deploy.sh
  on:
    branch: master