# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
addons:
  apt:
    packages:
      - jq
      - curl
install:
  - Rscript -e "install.packages('rsconnect')"
before_script: cd simple-rmd
script: ./deploy.sh
