# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - jq
      - curl
deploy:
  provider: script
  script: bash simple-rmd/deploy.sh
  on:
    branch: master